# .devcontainer/docker-compose.yml
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    shm_size: 2gb
    tty: true
    volumes:
      - ..:/home/user/workshop:cached
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 4g
        reservations:
          cpus: '0.25'
          memory: 4g
