# Start with a base Debian image
FROM debian:bookworm-slim

# Set environment variables to non-interactive (this prevents some prompts)
ENV DEBIAN_FRONTEND=noninteractive

# Update the package list and install necessary dependencies for building Python packages and zsh
# require root access
RUN apt-get update && \
    apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libreadline-dev \
    libffi-dev \
    curl \
    wget \
    zsh \
    git \
    autojump && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Download and install Python 3.12 from source (Python 3.12 is not currently avaialble in the Debian package repository)
WORKDIR /tmp
RUN wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz
RUN tar -xvf Python-3.12.0.tgz
WORKDIR /tmp/Python-3.12.0
RUN ./configure --enable-optimizations
RUN make altinstall
WORKDIR /
RUN rm -rf /tmp/Python-3.12.0

# Set Python 3.12 as the default Python version: requires root
RUN update-alternatives --install /usr/bin/python3 python3 /usr/local/bin/python3.12 1


# install sudo so we can create a non root account to use as default
RUN apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*

# Create a non-root user
ARG USERNAME=user
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME && \
    useradd --uid $USER_UID --gid $USER_GID -m $USERNAME && \
    echo "$USERNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USERNAME && \
    chmod 0440 /etc/sudoers.d/$USERNAME

# Install Miniforge
RUN wget https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh -O miniforge.sh && \
    sudo bash miniforge.sh -b -p /miniforge && \
    rm miniforge.sh && \
    . /miniforge/etc/profile.d/conda.sh && \
# update conda to the latest version
    conda update -n base -c conda-forge conda && \
# Prevent auto-activation of the base environment
    conda config --set auto_activate_base false

# Add Miniforge to PATH
ENV PATH="/miniforge/bin:${PATH}"

# Switch to non-root user
USER $USERNAME

# Create repos directory and clone the repositories
RUN mkdir /home/$USERNAME/repos && \
    git clone --branch master https://github.com/cogent3/EnsemblLite.git /home/$USERNAME/repos/EnsemblLite && \
    git clone --branch develop https://github.com/cogent3/cogent3.git /home/$USERNAME/repos/cogent3

# Create a new conda environment named c312
RUN . /miniforge/etc/profile.d/conda.sh && \
    conda create -n c312 python=3.12 -y && \
    conda activate c312 && \
    mamba install flit jupyter ipykernel unsync click 
    # cd /home/$USERNAME/repos/EnsemblLite && \
    # flit install -s --python $(which python) && \
    # cd /home/$USERNAME/repos/cogent3 && \
    # flit install -s --python $(which python)

# Initialize conda for bash shell interaction with c312 environment
RUN echo ". /miniforge/etc/profile.d/conda.sh" >> $HOME/.bashrc && \
    echo "conda activate c312" >> $HOME/.bashrc

# # Install cogent3 and EnsemblLite from the cloned repositories in the c312 environment
# RUN cd /home/$USERNAME/repos/EnsemblLite && \
#     flit install -s --python $(which python) && \
#     cd /home/$USERNAME/repos/cogent3 && \
#     flit install -s --python $(which python)
      
# Install Oh My Zsh
RUN sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

# Set zsh as the default shell
SHELL ["/usr/bin/zsh", "-c"]

# Create a default .zshrc file with some suggested configurations
RUN echo 'export ZSH="$HOME/.oh-my-zsh"' >> $HOME/.zshrc && \
    echo 'ZSH_THEME="robbyrussell"' >> $HOME/.zshrc && \
    echo 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting autojump)' >> $HOME/.zshrc && \
    echo 'source $ZSH/oh-my-zsh.sh' >> $HOME/.zshrc && \
    echo 'export HISTFILE=~/.zsh_history' >> $HOME/.zshrc && \
    echo 'export HISTSIZE=10000' >> $HOME/.zshrc && \
    echo 'export SAVEHIST=10000' >> $HOME/.zshrc && \
    echo 'setopt appendhistory' >> $HOME/.zshrc && \
    echo 'setopt histignorespace' >> $HOME/.zshrc && \
    echo 'setopt histignorealldups' >> $HOME/.zshrc && \
# Initialize conda for zsh shell interaction
    echo ". /miniforge/etc/profile.d/conda.sh" >> $HOME/.zshrc && \
    echo "conda activate c312" >> $HOME/.zshrc
    
# Install zsh-autosuggestions and zsh-syntax-highlighting plugins
RUN git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# Start a terminal session using the zsh shell
CMD ["/usr/bin/zsh"]