# .devcontainer/docker-compose.yml
version: '3.8'
services:
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    shm_size: '2gb'
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '4g'
        reservations:
          cpus: '1.0'
          memory: '2g'
    volumes:
      - ${localWorkspaceFolder}:/home/user/workshop:cached
