jobs:
  check-cpus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check number of CPUs
        run: |
          echo "Number of CPUs available:"
          nproc
