name: Build and Push Docker images

on:
  push:
    branches:
      - main
      - Build-container-images-in-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - dockerfile: Dockerfile
            image_tag: latest
          - dockerfile: Dockerfile.prepopulated
            image_tag: prepopulated

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: |
          docker build -f .devcontainer/${{ matrix.dockerfile }} . \
            -t ghcr.io/${{ github.repository_owner }}/cogent3-workshop:${{ matrix.image_tag }}

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/cogent3-workshop:${{ matrix.image_tag }}
